### ISSUE TITLE
create an organisation

### ISSUE THREAD

**Issue by vv01f** [RadicalMilitantLibrary/www#3]
I suggest to hold different parts (or even implementations) of the project in separate repositories besides to make it possible to organize rights management.

**Comment by Jotunbane** [comment]
done ... moved here : https://github.com/RadicalMilitantLibrary

**Comment by s72785** [comment]
er, actually that seems to be a copy – is that intended?
maybe you would prefer a [transfer](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-to-an-organization) instead while there is no or few difference still.
