### ISSUE TITLE
update preg_replace to preg_replace_callback for php7

### ISSUE THREAD

**Issue by shithead** [RadicalMilitantLibrary/www#74]
Warning: preg_replace(): The /e modifier is no longer supported, use preg_replace_callback instead in /usr/share/nginx/www-master/RML.helper.php on line 229

PHP Version 7.2

**Comment by Jotunbane** [comment]
thanks... we know.
pull requests are welcome ;)

**Comment by s72785** [comment]
The function `preg_replace` probably needs replacement in up to 42 cases.

@shithead as for the e modifier: its ignored and thus could be simply removed here.
The more concerning bug would be that the not sanitized digits for the function `chr` could exceed the defined range of 0-255. So probably we will find some more issues ahead :) .

Honestly I have no clue for what data (especially the first array entry `/'/`) was for…
To solve both things for the (2nd entry) HTML-escaped entities I would try: `preg_replace_callback("/(&#[0-9]+;)/", function($m) { return mb_convert_encoding($m[1], "UTF-8", "HTML-ENTITIES"); }, $input)`

… not tested of course.

**Comment by s72785** [comment]
as the mb module might not be available that function needs to be tested or provided as a reimplementation;

```
//~ if( !function_exists('mb_convert_encoding') ){
	//~ echo "fn missing\n";
	// implement or …
	//~ exit(1);	
//~ }
```

I am searching for a solution on that part.
 
```
function RMLpreparestring( $string )
{
	$result = preg_replace( "/'/", "''", $string ); //remains as no error|warning|notice reported
	$result = preg_replace_callback( '@&#(\d+);@', function($m){
		if ( $m[1] >= 0 && $m[1] <= 255 ) {return chr($m[1]);} // supports ascii only
	}, $string );
	return $result;
}
```

…should do as much as the broken one before. tested in php5 and php7.0 cli.

**Comment by s72785** [comment]
viable solution found:

```
$s="&#32;&#33;&#48;&#8222;test&#8220; &#9900;, not supporting hex: &#x255; &#xff;";
echo html_entity_decode($s, ENT_QUOTES | ENT_XML1, 'UTF-8')."\n";
```

results in:
```
 !0„test“ ⚬, not supporting hex: ɕ ÿ
```

for php5 and php7.0 on my cli.

**Comment by Jotunbane** [comment]
Meh.
We where too quick here.
This doesn't work.

**Comment by s72785** [comment]
@Jotunbane do you have sth. to test against?
